In [2]:
import pandas as pd
lotr1 = pd.read_csv("LOTR.csv")
lotr2 = pd.read_csv("LOTR_2.csv")
# A simple combination of the two tables
lotr_combined=pd.concat([lotr1, lotr2])
lotr_combined

   FellowshipID FirstName     Skills     Age
0          1001     Frodo     Hiding     NaN
1          1002   Samwise  Gardening     NaN
2          1003   Gandalf     Spells     NaN
3          1004    Pippin  Fireworks     NaN
0          1001     Frodo        NaN    50.0
1          1002   Samwise        NaN    39.0
2          1006   Legolas        NaN  2931.0
3          1007    Elrond        NaN  6520.0
4          1008  Barromir        NaN    51.0

In [3]:
#Only the entrys that are in both tables
lotr_inner=pd.merge(left=lotr1, right=lotr2, how='inner', on=['FellowshipID', "FirstName"])
lotr_inner

   FellowshipID FirstName     Skills  Age
0          1001     Frodo     Hiding   50
1          1002   Samwise  Gardening   39

In [4]:
#All the entries in either one of the two tables
lotr_outer=pd.merge(left=lotr1, right=lotr2, how='outer')
lotr_outer

   FellowshipID FirstName     Skills     Age
0          1001     Frodo     Hiding    50.0
1          1002   Samwise  Gardening    39.0
2          1003   Gandalf     Spells     NaN
3          1004    Pippin  Fireworks     NaN
4          1006   Legolas        NaN  2931.0
5          1007    Elrond        NaN  6520.0
6          1008  Barromir        NaN    51.0

In [5]:
#Only the rows in the right table, with data added from the left table (The skills column)
lotr_right=pd.merge(left=lotr1, right=lotr2, how='right')
lotr_right

   FellowshipID FirstName     Skills   Age
0          1001     Frodo     Hiding    50
1          1002   Samwise  Gardening    39
2          1006   Legolas        NaN  2931
3          1007    Elrond        NaN  6520
4          1008  Barromir        NaN    51

In [6]:
#Creating pairs of people
lotr_cross=pd.merge(left=lotr1, right=lotr2, how='cross')
lotr_cross

    FellowshipID_x FirstName_x     Skills  FellowshipID_y FirstName_y   Age
0             1001       Frodo     Hiding            1001       Frodo    50
1             1001       Frodo     Hiding            1002     Samwise    39
2             1001       Frodo     Hiding            1006     Legolas  2931
3             1001       Frodo     Hiding            1007      Elrond  6520
4             1001       Frodo     Hiding            1008    Barromir    51
5             1002     Samwise  Gardening            1001       Frodo    50
6             1002     Samwise  Gardening            1002     Samwise    39
7             1002     Samwise  Gardening            1006     Legolas  2931
8             1002     Samwise  Gardening            1007      Elrond  6520
9             1002     Samwise  Gardening            1008    Barromir    51
10            1003     Gandalf     Spells            1001       Frodo    50
11            1003     Gandalf     Spells            1002     Samwise    39
12            1003     Gandalf     Spells            1006     Legolas  2931
13            1003     Gandalf     Spells            1007      Elrond  6520
14            1003     Gandalf     Spells            1008    Barromir    51
15            1004      Pippin  Fireworks            1001       Frodo    50
16            1004      Pippin  Fireworks            1002     Samwise    39
17            1004      Pippin  Fireworks            1006     Legolas  2931
18            1004      Pippin  Fireworks            1007      Elrond  6520
19            1004      Pippin  Fireworks            1008    Barromir    51

In [7]:
#The two tables combined into one, with the same titled columns differentiated
lotr_join=lotr1.join(lotr2, lsuffix='_1', rsuffix="_2")
lotr_join

   FellowshipID_1 FirstName_1     Skills  FellowshipID_2 FirstName_2   Age
0            1001       Frodo     Hiding            1001       Frodo    50
1            1002     Samwise  Gardening            1002     Samwise    39
2            1003     Gandalf     Spells            1006     Legolas  2931
3            1004      Pippin  Fireworks            1007      Elrond  6520